import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        mainBG: "var(--mainBG)",
        sectionBG: "var(--sectionBG)",
        cardSmText: "var(--cardSmText)",
        borderCol: "var(--borderCol)",
        iconCol: "var(--iconCol)",
        inputFieldBG: "var(--inputFieldBG)",
        lineBorderCol: "var(--lineBorderCol)",
        errorCol: "var(--errorCol)",
        errorBG: "var(--errorBG)",
        hoverBG: "var(--hoverBG)",
        lightHoverBG: "var(--lightHoverBG)",
        highlightCol: "var(--highlightCol)",
        newGreen: "var(--newGreen)",
        sidebarText: "var(--sidebarText)",
        cardBackground: "var(--cardBackground)",
        successCol: "var(--successCol)",
        borderDefault: "var(--borderDefault)",
        buttonDisabledCol: "var(--buttonDisabledCol)",
        borderActive: "var(--borderActive)",
        borderMuted: "var(--borderMuted)",
        bgSubtle: "var(--bgSubtle)",
        bgElevated: "var(--bgElevated)",
        mainGreen: "var(--mainGreen)",
        loginBtn: "var(--loginBtn)",
        loginColor: "var(--loginColor)",
        secondaryCol: "var(--secondaryCol)",
        textTheme: "var(--textTheme)",
        bgAction: "var(--bgAction)",
        bgActionHover: "var(--bgActionHover)",
        textAction: "var(--textAction)",
        textActionHover: "var(--textActionHover)",
        btnThemeColor: "var(--btnThemeColor)",
        btnTheme: "var(--btnTheme)",
        notifRead: "var(--notifRead)",
        subTitleText: "var(--subTitleText)",
        borderDefault2: "var(--borderDefault2)",
        disabledBtnText: "var(--disabledBtnText)",
        disabledBtnBG: "var(--disabledBtnBG)",
        btnColor: "var(--btnColor)",
        redButton: "var(--redButton)",
        bgCanvas: "var(--bgCanvas)",
        bgField: "var(--bgField)",
        bgTextEditor: "var(--bgTextEditor)",
        bgSkeleton: "var(--bgSkeleton)",
        startButton: "var(--startButton)",
        gradeAText: "var(--gradeAText)",
        gradeBBg: "var(--gradeBBg)",
        gradeBText: "var(--gradeBText)",
        bgSubtle2: "var(--bgSubtle2)",
        chatBG : "var(--chatBG)"
      },
      screens: {
        'lg' : '1400px',
        'xl' : '1600px',
        '2xl': '1750px',
        '2.5xl': '1910px',
        '3xl': '2100px',
        '4xl': '2400px',
      },
      fontSize: {
        xxs: 'var(--fs-xxs)',
        xs: 'var(--fs-xs)',
        xsm : 'var(--fs-xsm)',
        sm: 'var(--fs-sm)',
        md: 'var(--fs-md)',
        lg: 'var(--fs-lg)',
        xl: 'var(--fs-xl)',
        '2xl': 'var(--fs-2xl)',
        '3xl': 'var(--fs-3xl)',
        '4xl': 'var(--fs-4xl)',
        '5xl': 'var(--fs-5xl)',
      },
      spacing: {
        0: 'var(--space-0)',
        '0.5': 'var(--space-0_5)',
        1: 'var(--space-1)',
        '1.5': 'var(--space-1_5)',
        2: 'var(--space-2)',
        '2.5': 'var(--space-2_5)',
        3: 'var(--space-3)',
        '3.5': 'var(--space-3_5)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
      },
    },
  },
  plugins: [
  ],
} satisfies Config;